### ISSUE TITLE
[Feature] Add a Docker Image

### ISSUE THREAD

**Issue by TheDanniCraft** [operational-co/operational.co#3]
Hi,

I’d like to contribute by adding a Docker image for this project. This would make it easier for users to run the application in a consistent (production) environment without needing to install dependencies manually.

Proposed Changes:

- Create a Dockerfile to containerize the application
- Provide a GitHub Actions workflow to build and publish the image automatically (I would suggest using GHCR (GitHub Container Registry) for that)

Would this be something you’re interested in? Let me know if you have any preferences regarding the base image or specific requirements.

Looking forward to your feedback!

**Comment by shash7** [comment]
Docker setup is nearly ready! Gimme a few days.

Not sure about github actions(never used it). If people are interested I can look into it.

**Comment by Codycody31** [comment]
Maybe a centralized docker image would be good? I know the project has the ability to build the app and backend but it would be way easier to deploy if it was one image, maybe using nginx or something else.

**Comment by Mgldvd** [comment]
Hope this helps

> .github/workflows/docker-build.yml

```yml
name: Docker image build and push

on:
  push:
    branches:
      - deploy/ghcr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🍋 - Login to GitHub Container Registry
        run: |
          docker login --username operational-co --password ${{ secrets.TOKEN_GITHUB_DOCKER }} ghcr.io

      - name: 🍄 - Build Docker image
        run: |
          docker build . -t ghcr.io/operational-co/operational.co:latest

      - name: 🍎 - Push Docker image
        run: |
          docker push ghcr.io/operational-co/operational.co:latest
```
